version: '3.9'
services:
    cache:
        image: redis:6.2-alpine
        restart: always
        ports:
        - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes: 
        - cache:/data
    app:
        build:
            context: "./"
            dockerfile: "Dockerfile"
        ports:
            - "80:5000"
        expose:
            - "5000"
        environment:
            NODE_ENV: production
            REDIS_HOST: cache
            REDIS_PORT: 6379
            REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        links:
            - cache
        volumes:
            - /repositories:/path/in/docker

volumes:
  cache:
    driver: local