version: '3'
services:
  nuxt-app:
    image: gorlanovs/cfjs:latest
    container_name: nuxt-app
    restart: always
    ports:
        - 3000:3000
    volumes:
        - ./repos:/repos
    networks:
        - nuxt-network
    environment:
        NODE_ENV: production
  web-server:
    image: nginx:1.17.10-alpine
    container_name: web-server
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 80:80
    networks:
        - nuxt-network
    depends_on:
        - nuxt-app
    restart: unless-stopped
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    networks:
    - nuxt-network
  mongodb:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sysadmin
      MONGO_INITDB_ROOT_PASSWORD: sysadmin
    ports:
      - "27017:27017"

networks:
  nuxt-network:
    driver: bridge